version: '2'
services:
  postgres:
    image: postgres:9.6.12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: database
    volumes:
      - ./restaurant_data/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
